[alias]
wasm = "build --release --lib --target wasm32-unknown-unknown"
unit-test = "test --lib"
integration-test = "test --lib integration_tests"
multitest = "test --test multitest"
clean-schema = "run-script clean-schema"
schema = "run-script generate-schema"
optimize = "run-script optimize-wasm"
